name: AnvilUI
version: 0.1
api: 3.0.0
main: Anvil\Anvil
author: Digueloulou12
depend:
  - FormAPI

commands:
  anvilreload:
    permission: "anvilreload.use"
    description: "Reload the configs of the AnvilUI plugin from Digueloulou12"
    usage: "/anvilreload"

permissions:
  anvilreload.use:
    description: "Give access to the command"
    default: "op"